import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Provider from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Full Stack Blog Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className='bg-[#fff]'>
                <Provider>
                    <main className='w-screen h-screen flex flex-col justify-between'>
                        <Navbar />
                        {children}
                        <Footer />
                    </main>
                </Provider>
            </body>
        </html>
    );
}
